# Created User
POST http://localhost:8084/api/v1/users/register
Accept: application/json
Content-Type: application/json

{
  "username":"userB",
  "email":"userB@gmail.com",
  "password":"password"
}
