name: tracker
description: Budget Tracking Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  fl_chart: ^0.36.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.0.0+2
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  local_auth: ^1.1.6
  lottie: ^1.1.0
  package_info_plus: ^1.0.4
  path_provider: ^2.0.5
  permission_handler: ^8.1.4+2
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  logger: ^1.0.0
  mockito: ^5.0.14

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animation/
    - assets/icon/
    - assets/image/
    - assets/language/
